services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    build:
      context: ./backend
    container_name: backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/library_management
      - JWT_SECRET=7841effa52b75452e8f7c48c81f995060417f375a8320dc6d00d1b2089b85207
      - PORT=5000
      - NODE_ENV=production
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=/api
    container_name: frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongodb_data:
